
var eng = { 
		"banner" : "It's time!",
		"home" : "Home",
		"schedule" : "Schedule",
		"transport" : "Transport",
		"food" : "Food and Allergies",
		"accomodation" : "Accomodation",
		"dresscode" : "Dresscode",
		"contact" : "Contact",
		"home_intro1" : "The wedding is closing in...",
		"home_intro2" : "We need to ...",
		"home_highlight" : "30th of April",
 		"home_pt1" : "If you ",
		"home_pt2" : "If you",
		"home_pt3" : "If you",
		"home_pt4" : "If you",
		"schedule_intro" : "",
		"schedule_15" : "",
		"schedule_1530" : "",
		"schedule_16" : "",
		"schedule_1730" : "",
		"schedule_20" : "",
		"schedule_21" : "",
		"schedule_23" : "",
		"schedule_0050" : "",
		"transport_intro" : "",
		"food_intro" : "",
		"accomodation_intro" : "",
		"dresscode_intro1" : "",
		"dresscode_h2" : "",
		"dresscode_intro2" : "",
		"dresscode_men1" : "",
		"dresscode_women1" : "",
		"dresscode_men2" : "",
		"dresscode_men3" : "",
		"dresscode_men4" : "",
		"contact_intro" : ""
 	}
