
var sve = { 
		"banner" :"Nu var det dags!",
		"home" : "Home",
		"schedule" : "Schema",
		"transport" : "Transport",
		"food" : "Dryck och Allergier",
		"accomodation" : "Boende",
		"dresscode" : "Dresscode",
		"contact" : "Kontakt",
		"home_intro1" : "Bröllopet närmar sig med stormsteg och vi ser jättemycket fram emot att ni ska komma och dela vår dag med oss! På denna sida kan ni hitta all viktig information om dagen. Tanken är att all information ni behöver ska finnas tillgänglig på denna hemsida. Nedan följer viktig information.",
		"home_intro2" : "Vi behöver att ni ",
		"home_highlight" : "senast 30e April meddelar oss:",
		"home_pt1" : "Om ni tar er ut själva eller vill åka med buss från Bro Station 15:00",
		"home_pt2" : "Om ni vill bo kvar tillsammans med oss på Görvälns Slott efteråt och hur många enkel/dubbelrum ni behöver (och då åker vi tillsammans med buss efter festens slut)",
		"home_pt3" : "Eventuella allergier",
		"home_pt4" : "Om ni främst dricker alkoholfritt eller alkoholhaltigt (man får dricka av båda alternativen men för kökets skull behöver ni meddela vilket ni föredrar mest)",
		"schedule_intro" : "Bröllopet kommer att hållas på Bro Hof Slott den 30e Juni 2018. Vigseln börjar 15:30 vilket följs av mingel och fördrink, middag, tårta och efterfest. Hela spektaklet slutar klockan 00:50, men de som känner sig färdiga tidigare eller har småbarn får avvika när ni behöver ^^",
		"schedule_15" : "Buss avgår från Bro Station till Bro Hof Slott",
		"schedule_1530" : "Vigsel startar på gräsmattan under eken (inomhus på övervåningen vid regn)",
		"schedule_16" : "Vigseln slutar. Bröllopsparet tar bröllopsbilder och gästerna minglar under tiden.",
		"schedule_1730" : "Middagen börjar på övervåningen.",
		"schedule_20" : "Tårta och avec följt av bröllopsdans.",
		"schedule_21" : "Middagen avslutas och efterfesten börjar.",
		"schedule_23" : "Efterfesten fortsätter och vickning serveras.",
		"schedule_0050" : "Festen avslutas och buss avgår till Görvälns Slott för övernattning.",
		"transport_intro" : "För er som vill åka själva med bil eller taxi går det självklart bra. För er som vill åka samlat kommer vi att anordna buss som åker från Bro Station klockan 15:00 till Bro Hof. Efter festens slut finns möjlighet att ta buss till Bro Station, och de som övernattar tillsammans med oss följer med samma buss vidare till Görvälns Slott.",
		"food_intro" : "Det kommer att finnas både alkoholfritt och alkoholhaltiga dryckesalternativ. Ni får självklart dricka från båda utbuden men meddela oss innan om ni främst dricker alkoholfritt eller alkoholhaltigt så mängderna kan planeras. Meddela även om ni har några allergier så att köket kan ordna annan mat vid behov.",
		"accomodation_intro" : "Vi har bokat boende på Görvälns Slott natten mellan lördag och söndag så att alla som vill kan stanna över natten och äta frukost tillsammans med oss morgonen efter. Meddela om ni vill stanna över natten och om ni vill ha ett enkelrum (1295 SEK) eller dubbelrum (1595 SEK) senast den 30e April. Betalning för rummen sker på plats samma dag. Incheckningen till hotellet sker vid lunch på lördagen. För de som vill finns möjlighet att sova där redan natten innan. Kontakta i detta fall Görvälns Slott på +46 8 120 002 00 eller hello@gorvalnsslott.se.",
		"dresscode_intro1" : "Klädkod brukar ofta ge många frågetecken när man går på bröllop då ettiketten på senare år har ändrats. Vi har valt att använda den engelska klädkoden",
		"dresscode_h2" : "Okej, men vad betyder detta?",
		"dresscode_intro2" : "Den korta versionen är:",
		"dresscode_men1" : "För herrar: Mörk kostym, alternativt smoking",
		"dresscode_women1" : "För damer: Festlig klänning (ej golvlång) alternativt kjol med topp",
		"dresscode_men2" : "För männen",
		"dresscode_men3" : "Mörk kostym och smoking har traditionellt sett aldrig blandats utan har varit antingen eller. Vi har valt att använda den engelska definitionen",
		"dresscode_men4" : "vilket innebär mer frihet för både damer och herrar. För männen innebär detta att man antingen kan ha mörk kostym (grå/blå/svart) eller ha svart/mörk smoking. ",
		"contact_intro" : "Om det är något som är oklart, om ni vill hålla tal, om ni har några funderingar kring presentlistan, eller om det är något annat som är oklart, så kan ni kontakta Toastmaster Erik Ferm på följande mai"


	}
